### ISSUE TITLE
[Bug] Seems to be a problem when Removing buttons

### ISSUE THREAD

**Issue by ZaneDragonBorn** [TomB-134/MinimalMenu#6] opened 2021-01-15 00:14 UTC
Removing random items will cause others to just go into each other. I'm thinking there may be an issue with Better Mod Button, but it may just be broken.

**Comment by jackassmc** [comment] 2021-05-19 03:42
This is a duplicate of https://github.com/TomB-134/MinimalMenu/issues/7.

**Closed** 2021-05-31 18:01 UTC
