### ISSUE TITLE
Visual bug with Mod Menu 1.15.0

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TomB-134/MinimalMenu#7] opened 2021-02-01 07:22 UTC
Using `minimalmenu-1.16.4-0.0.5`
```json
{
    "REMOVE_SPLASH": true,
    "REMOVE_EDITION": true,
    "REMOVE_SINGLEPLAYER": false,
    "REMOVE_MULTIPLAYER": false,
    "REMOVE_REALMS": true,
    "REMOVE_LANGUAGE": true,
    "REMOVE_ACCESSIBILITY": true,
    "REMOVE_COPYRIGHT": true,
    "STOP_SPIN": false,
    "X_OFFSET_TITLE": 0,
    "Y_OFFSET_TITLE": 0,
    "REMOVE_REALMS_NOTIF": true,
    "REMOVE_FEEDBACK": true,
    "REMOVE_BUGS": false,
    "REMOVE_LANSP": false,
    "REMOVE_LANMP": true,
    "X_OFFSET_PAUSE": 0,
    "Y_OFFSET_PAUSE": 0,
    "ADD_SAVES": true,
    "ADD_RELOAD_SAVES": true,
    "DEV_MODE": false
}
```
![screenshot](https://user-images.githubusercontent.com/618276/106426659-dd520780-641a-11eb-9581-a612cf4726b2.png)

**Comment by supersaiyansubtlety** [comment] 2021-02-01 07:24
[Issue on Mod Menu](https://github.com/TerraformersMC/ModMenu/issues/196)

**Comment by JeffAxe123** [comment] 2021-02-26 15:10
This is a critical bug

**Comment by RDKRACZ** [comment] 2021-03-04 22:38
Please fix this.

**Comment by RDKRACZ** [comment] 2021-03-05 13:40
Also happens when both remove feedback button and remove bug report button are enabled
![when remove feedback and bug report buttons are enabled](https://user-images.githubusercontent.com/43277609/110122923-8e541500-7dc0-11eb-978d-6401597ca7ba.png)

**Comment by Jefaxe** [comment] 2021-03-14 22:32
This basically breaks the entire mod

**Comment by RDKRACZ** [comment] 2021-03-14 22:33
Only when certain features are enabled but yes.

**Comment by jackassmc** [comment] 2021-05-19 03:37
This is caused by https://github.com/TerraformersMC/ModMenu/commit/3d28533183689fc9a3a4e55aed52bd2eeadf4fd3 switching ModMenu to the Farbric Screen API. This makes MinimalMenu run before ModMenu, which also causes https://github.com/TomB-134/MinimalMenu/issues/19.

**Comment by TomB-134** [comment] 2021-05-31 19:35
A whooping 5 months later, I have appeared. I went on a bit of a bug squashing spree tonight, the only issues left are feature requests and this bug. I haven't had much time to look into this but from the fantastic work by @jackassmc it sounds like this is a mod menu issue? 

For now on 1.16 at least, I'd just use v1.14 of mod menu. Sounds like updating to 1.17 might be more of a pain than I thought.

**Comment by jackassmc** [comment] 2021-06-03 02:57
It's a compatibility issue between MinimalMenu and ModMenu, it can be fixed on either side. I made a PR for ModMenu https://github.com/TerraformersMC/ModMenu/pull/258 that would fix it on that side but Prospector, the main developer of ModMenu, has stepped back from modding Minecraft so that PR is in limbo atm.

To fix this in MinimalMenu the button logic has to run after ModMenu has added the Mods button. ModMenu adds the button after `Screen.init` which calls `this.init` which is what MinimalMenu uses (`TitleScreen.init` and `GameMenuScreen.initWidgets` (called from `GameMenuScreen.init`)) so MinimalMenu always runs before ModMenu. To fix this MinimalMenu could be restructured to also mixin `Screen.init` with a higher priority (which confusingly makes it run later).

Something along the lines of this should work:
```java
@Mixin(value = Screen.class, priority = 1100)
public abstract class Screen extends AbstractParentElement implements TickableElement, Drawable {
    @Inject(method = "init", at = @At("TAIL"))
    private void init(MinecraftClient client, int width, int height, CallbackInfo info) {
        if ((Screen)(Object)this instanceof TitleScreen) {
            // TitleScreen button logic here
        } else if ((Screen)(Object)this instanceof GameMenuScreen) {
            // GameMenuScreen button logic here
        }
    }
}
```

**Closed** 2021-06-03 23:57 UTC
Labels: help wanted
